#!/bin/sh

set -eu

provider=$1
name=$2
boxname="test-$name"
boxfile=$3

testdir=test-$name

cleanup() {
  set -x
  if [ -f $testdir/Vagrantfile ]; then
    (cd $testdir && vagrant destroy -f)
  fi
  rm -rf $testdir
  vagrant box remove $boxname || true
}
trap cleanup INT TERM EXIT

set -x
export VAGRANT_DEFAULT_PROVIDER="$provider"
vagrant box add $boxname $boxfile
mkdir $testdir
cp ../helpers/package_report $testdir
(
  cd $testdir
  vagrant init $boxname
  vagrant up --no-provision
  vagrant ssh -- true
  vagrant ssh -- sudo true
  vagrant ssh -- cat /etc/debian_version
  vagrant ssh -c "sh /vagrant/package_report"
  vagrant ssh -c "sudo apt-get --quiet --yes install figlet \
     && ( lsb_release --release --codename ) | figlet"
)
