#!/bin/sh

set -e

fs="$1"
hostname="$2"
if [ -z "$fs" ]; then
  echo "usage: $0 ROOTFS [HOSTNAME]"
  exit 1
fi

set -x

#######################################################################
# upgrade Debian images as the LXC template does not do it.
#######################################################################
printf '#!/bin/sh\nexit 101\n' > $fs/usr/sbin/policy-rc.d
chmod +x $fs/usr/sbin/policy-rc.d
echo 'Acquire::Languages "none";' > $fs/etc/apt/apt.conf.d/99translations
chroot $fs apt-get update
chroot $fs apt-get -qy dist-upgrade
rm -f $fs/usr/sbin/policy-rc.d

#######################################################################
# setup root user
#######################################################################
mkdir -p $fs/root/.ssh
chmod 700 $fs/root/.ssh
cat > $fs/root/.ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOF
chmod 600 $fs/root/.ssh/authorized_keys

#######################################################################
# setup vagrant user
#######################################################################
chroot $fs useradd --uid 1000 --shell /bin/bash vagrant
mkdir -p $fs/home/vagrant
chroot $fs chown vagrant:vagrant /home/vagrant
mkdir -p $fs/home/vagrant/.ssh
chmod 700 $fs/home/vagrant/.ssh
cat > $fs/home/vagrant/.ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOF
chmod 600 $fs/home/vagrant/.ssh/authorized_keys
chroot $fs chown -R vagrant:vagrant /home/vagrant/.ssh

#######################################################################
# setup passwordless sudo for vagrant user
#######################################################################
chroot $fs apt-get install -qy sudo
chroot $fs apt-get clean
cat > $fs/etc/sudoers.d/vagrant <<EOF
vagrant ALL=(ALL) NOPASSWD:ALL
EOF
chmod 0440 $fs/etc/sudoers.d/vagrant

#######################################################################
# setup hostname
#######################################################################
if [ -n "$hostname" ]; then
  echo "$hostname" > $fs/etc/hostname
fi
